### ISSUE TITLE
Too good

### ISSUE THREAD

**Issue by Codeman655** [Fauntleroy/GIFit#32]
This service is too good. I've been using it to up my karma game on Reddit and now and I'm too popular. I've created my own subreddit but it got too much traction from the haters and had to be put down. Please, make the product a little worse so that my quality of life can improve.

**Comment by Fauntleroy** [comment]
But alas, GIFit! still needs to improve! Check out the list:

- The library that actually compiles GIFs doesn't handle the `do not dispose` property properly, so GIFs are way bigger than they should be
- It also does not properly let you specify the color palette (meaning every GIF is 256 colors for better or worse)
- There's no way to add text!
- The GIFs only exist locally, GIFit! should definitely integrate with something like Giphy or Imgur!

True, GIFit! is an amazing accomplishment that will make you popular with all of your friends forever, but there's room for more popularness. We must all come together and face the problems that lie in front of us.
